import {
  Settings,
  Microscope,
  Earth,
  FlaskConical,
  Hash,
  Cloud,
  Mountain,
  Bug,
  Book,
  Baby,
  Torus,
} from "lucide-react";

export const scienceCategories = {
  Astronomy: {
    icon: Earth,
    items: [
      { title: "Axial Tilt", url: "/astronomy/axial-tilt" },
      { title: "Day", url: "/astronomy/day" },
      { title: "Exoplanets", url: "/astronomy/exoplanets" },
      { title: "Full Moon", url: "/astronomy/full-moon" },
      { title: "Kelvin", url: "/astronomy/kelvin" },
      { title: "Magnetosphere", url: "/astronomy/magnetosphere" },
      { title: "Meteorites", url: "/astronomy/meteorites" },
      { title: "Moonlight", url: "/astronomy/moonlight" },
      { title: "Multi-Star System", url: "/astronomy/multi-star" },
      { title: "Planetary Orbits", url: "/astronomy/planetary-orbits" },
      { title: "Planets", url: "/astronomy/planets" },
      { title: "Red Giant", url: "/astronomy/red-giant" },
      { title: "Sirius", url: "/astronomy/sirius" },
      { title: "Solar Flare", url: "/astronomy/solar-flare" },
      { title: "Starlight", url: "/astronomy/starlight" },
      { title: "Stars", url: "/astronomy/stars" },
      { title: "Stars Wobble", url: "/astronomy/stars-wobble" },
      { title: "Sunlight", url: "/astronomy/sunlight" },
      { title: "Tidal Locking", url: "/astronomy/tidal-locking" },
      { title: "Venus", url: "/astronomy/venus" },
    ],
  },
  Biology: {
    icon: Microscope,
    items: [
      { title: "Alzheimer's", url: "/biology/alzheimer" },
      { title: "Antioxidants", url: "/biology/antioxidants" },
      { title: "Bacteria", url: "/biology/bacteria" },
      { title: "Bioluminescence", url: "/biology/bioluminescence" },
      { title: "Breastfeeding", url: "/biology/breastfeeding" },
      { title: "Colors", url: "/biology/colors" },
      { title: "Evolution", url: "/biology/evolution" },
      { title: "Fasting", url: "/biology/fasting" },
      { title: "Fats", url: "/biology/fats" },
      { title: "Fear", url: "/biology/fear" },
      { title: "Fig", url: "/biology/fig" },
      { title: "Frost", url: "/biology/frost" },
      { title: "Gardens", url: "/biology/gardens" },
      { title: "Honey", url: "/biology/honey" },
      { title: "Hypoxia", url: "/biology/hypoxia" },
      { title: "Keraunoparalysis", url: "/biology/keraunoparalysis" },
      { title: "Nutrient Cycle", url: "/biology/nutrient-cycle" },
      { title: "Plant Stress", url: "/biology/plant-stress" },
      { title: "Pollination", url: "/biology/pollination" },
      { title: "White Hair", url: "/biology/white-hair" },
    ],
  },
  Chemistry: {
    icon: FlaskConical,
    items: [
      { title: "Celsius", url: "/chemistry/celsius" },
      { title: "Chlorophyll", url: "/chemistry/chlorophyll" },
      { title: "Fluorescence", url: "/chemistry/fluoresence" },
      { title: "Halocline", url: "/chemistry/halocline" },
      { title: "Hydrogen", url: "/chemistry/hydrogen" },
      { title: "Hydrogen Peroxide", url: "/chemistry/hydrogen-peroxide" },
      { title: "Iron", url: "/chemistry/iron" },
      { title: "Pyramids", url: "/chemistry/pyramids" },
      { title: "Pyritized Fossils", url: "/chemistry/pyritized-fossils" },
      { title: "Rust", url: "/chemistry/rust" },
      { title: "Superionic Water", url: "/chemistry/superionic-water" },
      { title: "Viscosity", url: "/chemistry/viscosity" },
    ],
  },
  Cosmology: {
    icon: Torus,
    items: [
      { title: "Age Of Universe", url: "/cosmology/age-of-universe" },
      { title: "Big Bang", url: "/cosmology/big-bang" },
      { title: "Big Crunch", url: "/cosmology/big-crunch" },
      { title: "Dark Energy", url: "/cosmology/dark-energy" },
      {
        title: "Equivalence Principle",
        url: "/cosmology/equivalence-principle",
      },
      { title: "Expanding Universe", url: "/cosmology/expanding-universe" },
      { title: "Galaxy Filaments", url: "/cosmology/galaxy-filaments" },
      { title: "Gravitation Waves", url: "/cosmology/gravitation-waves" },
      { title: "Gravity", url: "/cosmology/gravity" },
      { title: "Isotropy", url: "/cosmology/isotropy" },
      { title: "Primordial Smoke", url: "/cosmology/primordial-smoke" },
      { title: "Red Shifting", url: "/cosmology/red-shifting" },
      { title: "Seven Heavens", url: "/cosmology/seven-heavens" },
      { title: "Shape of Universe", url: "/cosmology/shape-of-universe" },
      { title: "Sound Waves", url: "/cosmology/sound-waves" },
      { title: "Spacetime", url: "/cosmology/spacetime" },
      { title: "Time Dilation", url: "/cosmology/time-dilation" },
    ],
  },
  Embryology: {
    icon: Baby,
    items: [
      { title: "Amniotic Fluids", url: "/embroyology/amniotic-fluid" },
      { title: "Bones", url: "/embroyology/bones" },
      { title: "Fetal Development", url: "/embroyology/fetal-development" },
      { title: "Gender", url: "/embroyology/gender" },
      { title: "Human Embryo", url: "/embroyology/human-embryo" },
      { title: "Human Senses", url: "/embroyology/human-senses" },
      { title: "Male Fertility", url: "/embroyology/male-fertility" },
      { title: "Meiosis", url: "/embroyology/meiosis" },
      { title: "Miscarriage", url: "/embroyology/miscarriage" },
      { title: "Sperm", url: "/embroyology/sperm" },
      { title: "Womb", url: "/embroyology/womb" },
    ],
  },
  Geology: {
    icon: Mountain,
    items: [
      { title: "Aftershocks", url: "/geology/aftershocks" },
      { title: "Asthenosphere", url: "/geology/asthenosphere" },
      { title: "Coal", url: "/geology/coal" },
      { title: "Dead Sea", url: "/geology/dead-sea" },
      { title: "Earth", url: "/geology/earth" },
      { title: "Earthquake", url: "/geology/earthquake" },
      { title: "Fault Lines", url: "/geology/fault-lines" },
      { title: "Hydrothermal Vents", url: "/geology/hydrothermal-vents" },
      { title: "Internal Mountains", url: "/geology/internal-mountains" },
      { title: "Internal Waves", url: "/geology/internal-waves" },
      { title: "Landslides", url: "/geology/landslides" },
      { title: "Minerals", url: "/geology/minerals" },
      { title: "Mountain", url: "/geology/mountain" },
      { title: "Photic Zone", url: "/geology/photic-zone" },
      { title: "Porous Rocks", url: "/geology/porous-rocks" },
      { title: "Pumice", url: "/geology/pumice" },
      { title: "Sinkhole", url: "/geology/sinkhole" },
      { title: "Soil Expansion", url: "/geology/soil-expansion" },
      { title: "Steam Explosions", url: "/geology/steam-explosions" },
      { title: "Subduction", url: "/geology/subduction" },
      { title: "Subductions", url: "/geology/subductions" },
      { title: "Tectonics", url: "/geology/tectonics" },
      { title: "Volcano", url: "/geology/volcano" },
      { title: "Weathering & Erosions", url: "/geology/weathering-erosions" },
    ],
  },
  History: {
    icon: Book,
    items: [
      { title: "Calendar", url: "/history/calendar" },
      { title: "Crucifixtion", url: "/history/crucifixtion" },
      { title: "Deities", url: "/history/deities" },
      { title: "Door Locks", url: "/history/door-locks" },
      { title: "Dried River", url: "/history/dried-river" },
      { title: "Flight", url: "/history/flight" },
      { title: "Haman", url: "/history/haman" },
      { title: "Karnak Temple", url: "/history/karnak-temple" },
      { title: "Moses", url: "/history/moses" },
      { title: "Mourning of Pharoah", url: "/history/mourning-of-pharoah" },
      { title: "Noah", url: "/history/noah" },
      { title: "North", url: "/history/north" },
      { title: "Paper Money", url: "/history/paper-money" },
      { title: "Petra", url: "/history/petra" },
      { title: "Pharoah", url: "/history/pharoah" },
      { title: "Pharoah Mummy", url: "/history/pharoah-mummy" },
      { title: "Pompie", url: "/history/pompie" },
      { title: "Prostrations", url: "/history/prostrations" },
      { title: "Skydiving", url: "/history/skydiving" },
      { title: "Ubar", url: "/history/ubar" },
    ],
  },
  Math: {
    icon: Hash,
    items: [
      { title: "Abjad Numerals", url: "/math/abjad-numerals" },
      { title: "Base 19", url: "/math/base-19" },
      { title: "Digital Books", url: "/math/digital-books" },
      { title: "Encoding", url: "/math/encoding" },
      { title: "Euler", url: "/math/euler" },
      { title: "Hypersonic", url: "/math/hypersonic" },
      { title: "Kilometer", url: "/math/kilometer" },
      { title: "Light Year", url: "/math/light-year" },
      { title: "Meter", url: "/math/meter" },
      { title: "Miles", url: "/math/miles" },
      { title: "Pi", url: "/math/pi" },
      { title: "Prime Numbers", url: "/math/prime-number" },
      { title: "Pulsar Navigation", url: "/math/pulsar-navigation" },
    ],
  },
  Meteorology: {
    icon: Cloud,
    items: [
      { title: "Acid Rain", url: "/meteorology/acid-rain" },
      { title: "Atmosphere", url: "/meteorology/atmosphere" },
      {
        title: "Atmospheric Pressure",
        url: "/meteorology/atmospheric-pressure",
      },
      { title: "Cloud Seeding", url: "/meteorology/cloud-seeding" },
      { title: "Desertification", url: "/meteorology/desertifiction" },
      { title: "Dew", url: "/meteorology/dew" },
      { title: "Fire Whirl", url: "/meteorology/fire-whirl" },
      { title: "Flash Flood", url: "/meteorology/flash-flood" },
      { title: "Fresh Water", url: "/meteorology/freshwater" },
      { title: "Frost Weathering", url: "/meteorology/frost-weathering" },
      { title: "Microburst", url: "/meteorology/microburst" },
      { title: "Orographic Effect", url: "/meteorology/orographic-effect" },
      { title: "Sea Breeze", url: "/meteorology/sea-breeze" },
      { title: "Shoreline", url: "/meteorology/shorline" },
      { title: "Water", url: "/meteorology/water" },
      { title: "Water Cycle", url: "/meteorology/water-cycle" },
      { title: "Weight of Clouds", url: "/meteorology/weight-of-clouds" },
      { title: "Wind", url: "/meteorology/wind" },
    ],
  },
  Physics: {
    icon: Settings,
    items: [
      { title: "Armor Piercing", url: "/physics/armor-piercing" },
      { title: "Atom", url: "/physics/atom" },
      { title: "Cold Plasma", url: "/physics/cold-plasma" },
      { title: "Light", url: "/physics/light" },
      { title: "Mass", url: "/physics/mass" },
      { title: "Pairs", url: "/physics/pairs" },
      { title: "Pulsar", url: "/physics/pulsar" },
      { title: "Rayleigh Scattering", url: "/physics/rayleigh-scattering" },
      { title: "Singularity", url: "/physics/singularity" },
      { title: "Solar Energy", url: "/physics/solar-energy" },
      { title: "Sonic Weapons", url: "/physics/sonic-weapons" },
      { title: "Speed of Light", url: "/physics/speed-of-light" },
      { title: "String Theory", url: "/physics/string-theory" },
      { title: "Terminal Velocity", url: "/physics/terminal-velocity" },
      { title: "Work", url: "/physics/work" },
      { title: "Wormhole", url: "/physics/wormhole" },
    ],
  },
  Physiology: {
    icon: Microscope,
    items: [
      { title: "AMD", url: "/physiology/amd" },
      { title: "Bedsores", url: "/physiology/bedsores" },
      { title: "Brain Cells", url: "/physiology/brain-cells" },
      { title: "Brain Function", url: "/physiology/brain-function" },
      { title: "Brain Stem", url: "/physiology/brain-stem" },
      { title: "Brainstem", url: "/physiology/brainstem" },
      { title: "Cataracts", url: "/physiology/cataracts" },
      { title: "Cholesterol", url: "/physiology/cholesterol" },
      { title: "Cholestrol", url: "/physiology/cholestrol" },
      { title: "Ear Drum", url: "/physiology/ear-drum" },
      { title: "Finger Prints", url: "/physiology/fingerprints" },
      { title: "Flash Blindness", url: "/physiology/flash-blindness" },
      { title: "Inner Ear", url: "/physiology/inner-ear" },
      { title: "Milk", url: "/physiology/milk" },
      { title: "Neurons", url: "/physiology/neurons" },
      { title: "Pupils", url: "/physiology/pupils" },
      { title: "Reading", url: "/physiology/reading-wisdom" },
      { title: "Skin Nerves", url: "/physiology/skin-nerves" },
      { title: "Vision Space", url: "/physiology/vision-space" },
    ],
  },
  Zoology: {
    icon: Bug,
    items: [
      { title: "Animal Language", url: "/zoology/animal-language" },
      { title: "Ants", url: "/zoology/ants" },
      { title: "Camels", url: "/zoology/camels" },
      { title: "Colonies", url: "/zoology/colonies" },
      { title: "Crow", url: "/zoology/crow" },
      { title: "Exoskeleton", url: "/zoology/exoskeleton" },
      { title: "Exskeleton", url: "/zoology/exskeleton" },
      { title: "Fossils", url: "/zoology/fossils" },
      { title: "Honey Bees", url: "/zoology/honey-bees" },
      { title: "Housefly", url: "/zoology/housefly" },
      { title: "Magnetoreception", url: "/zoology/magnetoreception" },
      { title: "Mosquito", url: "/zoology/mosquito" },
      { title: "Raptor", url: "/zoology/raptor" },
      { title: "Spider Web", url: "/zoology/spider-web" },
    ],
  },
};
